"""Add isolated fixture still curation provenance and immutable export admissions.

Actual predecessor verified with alembic heads before implementation.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = '5f60718293a4'
down_revision = '4e5f60718293'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curation_dataset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_root', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_device', sa.Integer(), nullable=False),
    sa.Column('source_inode', sa.Integer(), nullable=False),
    sa.Column('store_root', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_device', sa.Integer(), nullable=False),
    sa.Column('store_inode', sa.Integer(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curation_grant',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('disclosure', sa.Boolean(), nullable=False),
    sa.Column('operations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['curation_dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_sha256')
    )
    op.create_index(op.f('ix_curation_grant_dataset_id'), 'curation_grant', ['dataset_id'], unique=False)
    op.create_table('curation_source',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('split', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lineage_known', sa.Boolean(), nullable=False),
    sa.Column('generative', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['curation_dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_source_dataset_id'), 'curation_source', ['dataset_id'], unique=False)
    op.create_table('curation_artifact',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pixel_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('generative', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['curation_dataset.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['curation_artifact.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['curation_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'source_id', 'cache_key')
    )
    op.create_index(op.f('ix_curation_artifact_dataset_id'), 'curation_artifact', ['dataset_id'], unique=False)
    op.create_table('curation_operation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('manifest_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['curation_dataset.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['curation_grant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_id', 'kind', 'idempotency_key')
    )
    op.create_index(op.f('ix_curation_operation_dataset_id'), 'curation_operation', ['dataset_id'], unique=False)
    op.create_table('curation_caption',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artifact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['curation_artifact.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['curation_dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_caption_dataset_id'), 'curation_caption', ['dataset_id'], unique=False)
    op.create_table('curation_event',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['curation_operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_event_operation_id'), 'curation_event', ['operation_id'], unique=False)
    op.create_table('curation_review',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artifact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caption_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caption_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['curation_artifact.id'], ),
    sa.ForeignKeyConstraint(['caption_id'], ['curation_caption.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['curation_dataset.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['curation_grant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_review_dataset_id'), 'curation_review', ['dataset_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # Test/empty DB only: never erase accumulated provenance on rollback.
    bind = op.get_bind()
    for table in ('curation_dataset','curation_grant','curation_source','curation_artifact','curation_caption','curation_review','curation_operation','curation_event',):
        if bind.execute(sa.text("SELECT COUNT(*) FROM " + table)).scalar():
            raise RuntimeError("Refusing downgrade with curation provenance; disable the feature instead")
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curation_review_dataset_id'), table_name='curation_review')
    op.drop_table('curation_review')
    op.drop_index(op.f('ix_curation_event_operation_id'), table_name='curation_event')
    op.drop_table('curation_event')
    op.drop_index(op.f('ix_curation_caption_dataset_id'), table_name='curation_caption')
    op.drop_table('curation_caption')
    op.drop_index(op.f('ix_curation_operation_dataset_id'), table_name='curation_operation')
    op.drop_table('curation_operation')
    op.drop_index(op.f('ix_curation_artifact_dataset_id'), table_name='curation_artifact')
    op.drop_table('curation_artifact')
    op.drop_index(op.f('ix_curation_source_dataset_id'), table_name='curation_source')
    op.drop_table('curation_source')
    op.drop_index(op.f('ix_curation_grant_dataset_id'), table_name='curation_grant')
    op.drop_table('curation_grant')
    op.drop_table('curation_dataset')
    # ### end Alembic commands ###
